### ISSUE TITLE
Status 500 on localhost

### ISSUE THREAD

**Issue by vladimir-sama** [ghoshRitesh12/aniwatch-api#79]
### Describe the bug

http://localhost:4000/api/v2/hianime/search?q=eminence

### Expected behavior

Not really sure, results

### Actual behavior

```
{"status":500,"message":"getAnimeSearchResults: fetchError: Something went wrong"}
```
In browser and failed Python Requests GET
```
> aniwatch-api@2.1.0 start
> tsx src/server.ts

aniwatch-api at http://localhost:4000
<-- GET /api/v2/hianime/search
{
  "status": 500,
  "scraper": "getAnimeSearchResults",
  "message": "getAnimeSearchResults: fetchError: Something went wrong"
}
_HiAnimeError: getAnimeSearchResults: fetchError: Something went wrong
    at _HiAnimeError.wrapError (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/aniwatch/dist/index.js:171:14)
    at _getAnimeSearchResults (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/aniwatch/dist/index.js:586:24)
    at async <anonymous> (/mnt/secondary/Documents/Python/Anime Boa/aniwatch-api/src/routes/hianime.ts:64:16)
    at async dispatch (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/compose.js:30:17)
    at async cors2 (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/middleware/cors/index.js:74:5)
    at async dispatch (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/compose.js:30:17)
    at async logger2 (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/middleware/logger/index.js:39:5)
    at async dispatch (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/compose.js:30:17)
    at async file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/hono/dist/hono-base.js:195:25
    at async responseViaResponseObject (file:///mnt/secondary/Documents/Python/Anime%20Boa/aniwatch-api/node_modules/@hono/node-server/dist/index.mjs:342:13) {
  scraper: 'getAnimeSearchResults',
  status: 500
}
```
In terminal

### Additional context

Did `git clone` `npm i` `npm start` on Linux here (Artix)

**Comment by vladimir-sama** [comment]
Update: editing some `index.js` line 134 the timeout,
```
var clientConfig = {
  timeout: 99999,
...
```
After some many seconds the response came, however anyone knows why is it so slow? On browser too..
Will close since this isn't an actual bug

**Comment by ghoshRitesh12** [comment]
> Update: editing some `index.js` line 134 the timeout,
> ```
> var clientConfig = {
>   timeout: 99999,
> ...
> ```
> After some many seconds the response came, however anyone knows why is it so slow? On browser too..
> Will close since this isn't an actual bug

@vladimir-sama It could be because of hianime
