### ISSUE TITLE
Streaming link Not Working

### ISSUE THREAD

**Issue by ashishranjan3** [ghoshRitesh12/aniwatch-api#8]
### Describe the bug

streaming link while dunning the code locally is not working..while trying the same episode with same server with the render link provided by you is working  perfectly..maybe you forgot to update the code

### Expected behavior

http://localhost:4000/anime/episode-srcs?id=bleach-806?ep=13793&server=vidstreaming&category=dub

all other endpoints are working perfectly only the streaming is not working...tried with other animes as well

### Actual behavior

{
    "status": 500,
    "message": "Something went wrong"
}

error log

ET /anime/servers?episodeId=bleach-806?ep=13793 200 547.424 ms - 309
https://aniwatch.to/watch/bleach-806?ep=13793
THE SERVER:  vidstreaming
SERVER_ID:  578153
THE LINK:  https://megacloud.tv/embed-2/e-1/g5Ngl3J3Qtcq?k=1
connect ETIMEDOUT 2405:200:1607:2820:41::36:443
AxiosError: connect ETIMEDOUT 2405:200:1607:2820:41::36:443
    at AxiosError.from (file:///D:/code/arj-dev/aniwatch-api/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (file:///D:/code/arj-dev/aniwatch-api/node_modules/axios/lib/adapters/http.js:606:25)
    at RedirectableRequest.emit (node:events:514:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at eventHandlers.<computed> (D:\code\arj-dev\aniwatch-api\node_modules\follow-redirects\index.js:14:24)  
    at ClientRequest.emit (node:events:514:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:514:28)
    at TLSSocket.emit (node:domain:489:12) {
  port: 443,
  address: '2405:200:1607:2820:41::36',
  syscall: 'connect',
  code: 'ETIMEDOUT',
  errno: -4039,
  config: {
    transitional: {

**Comment by ghoshRitesh12** [comment]
I tested this locally, and it's working for me. 
Try again maybe
